name: Publish Package to NPM with alpha tag

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'alpha')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.7.6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm i
      - run: pnpm publish --no-git-checks --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
